### ISSUE TITLE
Trouble connecting to ADB server on OS X

### ISSUE THREAD

**Issue by PhilippCh** [quamotion/madb#29]
Hi there!

I'm currently looking into porting my codebase (C# .NET Framework 4.5.2 with VS2015) to OS X (and further Linux) and I'm running into an issue while connecting to the ADB server using `AdbClient.Instance.Connect(hostname);` where hostname is a local network IP á la 192.168.0.x.

The error returned is

``` C#
[ERROR] FATAL UNHANDLED EXCEPTION: System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x86a98c0 + 0x00167> in <filename unknown>:0 
  at SharpAdbClient.TcpSocket.Connect (System.Net.EndPoint endPoint) <0x86a9868 + 0x0001f> in <filename unknown>:0 
  at SharpAdbClient.AdbSocket..ctor (System.Net.EndPoint endPoint) <0x86a75c8 + 0x0007c> in <filename unknown>:0 
  at SharpAdbClient.Factories+<>c.<Reset>b__17_0 (System.Net.EndPoint endPoint) <0x86a7580 + 0x0002f> in <filename unknown>:0 
  at SharpAdbClient.AdbClient.Connect (System.Net.DnsEndPoint endpoint) <0x86b4570 + 0x00039> in <filename unknown>:0 
  at SharpAdbClient.AdbClientExtensions.Connect (IAdbClient client, System.String host) <0x86b4390 + 0x00076> in <filename unknown>:0 
  at CoCB.Utils.AdbHelper.ConnectToHost (System.String hostname) <0x86b4330 + 0x0001b> in <filename unknown>:0 
  at CoCB.Utils.AdbHelper.Connect () <0x86b4298 + 0x0006b> in <filename unknown>:0 
  at CoCB.Program.Main () <0x6bdf38 + 0x0012b> in <filename unknown>:0 
```

The same code is confirmed to work on Windows 10. I can see that under Unix based operating systems, you take a different approach to connecting to the ADB server, which connects to a socket at "/tmp/5037". I'm not very proficient with *nix sockets, so I don't know if I'm doing something wrong here. I can't find the requested socket file in the file system (through Finder or ls).

The server is started through `AdbServer.StartServer("/Users/xxx/Library/Android/sdk/platform-tools/adb", true);` and returns code 'Started' so I'm assuming the server was started successfully. But somehow the connection still fails. If I try to open a connection with 

``` C#
var socket = new Socket (AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.IP);

socket.Connect ("192.168.0.106", 5555);
```

the connection opens just fine (socket.Connected is True).

Would you have any idea where I could start with this?

Cheers
Philipp

**EDIT**

Replacing TcpSocket.cs

``` C#
//this.socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.IP);
this.socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
```

and AdbServer.cs

``` C#
//EndPoint = new UnixEndPoint($"/tmp/{AdbServerPort}");
EndPoint = new IPEndPoint(IPAddress.Loopback, AdbServerPort);
```

seems to connect to the device. I can query the DeviceData class, but I haven't tried sending any commands yet. Is there any specific reason you are using Mono.Posix specific endpoints for OS X and Linux?

**Comment by qmfrederik** [comment]
Hi @PhilippCh ,

Thanks for the detailed bug report!

I looked into this, and you are correct, a normal TCP endpoint is used by adb on all systems.

I was misled by the one exception - Debian (and hence also Ubuntu) [has manually patched adb](https://anonscm.debian.org/cgit/android-tools/android-tools.git/tree/debian/patches/use-local-socket.patch?h=debian/5.1.1.r29-2) to listen on local TCP sockets and Ubuntu was the Unix system on which we tested.

So the correct behavior would be to use TCP sockets on all operating systems, except for Debian Linux and derivatives.

I'll fix it for OS X, and keep this issue open to track a solution for Linux.

**Comment by qmfrederik** [comment]
For OS X, should be fixed by v[2.0.247](https://www.nuget.org/packages/sharpadbclient/2.0.247) of our NuGet package. Let me know if this helps.

**Comment by PhilippCh** [comment]
Unfortunately, this does not solve the problem. PlatformID on many OS X devices is still returned as PlatformID.Unix.

Here's a fixed version of `Environment.OSVersion.Platform` that checks whether certain Mac-specific directories exist on the machine. I would create a pull request, but I'm not sure whether you'd want to include this "hack" in the official version.
```C#
public static PlatformID GetCurrentPlatform() {
            var platformId = Environment.OSVersion.Platform;

            if (platformId == PlatformID.Unix) {

                // Well, there are chances MacOSX is reported as Unix instead of MacOSX.
                // Instead of platform check, we'll do a feature checks (Mac specific root folders)
                if (Directory.Exists("/Applications")
                    & Directory.Exists("/System")
                    & Directory.Exists("/Users")
                    & Directory.Exists("/Volumes")) {

                    platformId = PlatformID.MacOSX;
                }
            }

            return platformId;
        }
```

**Comment by qmfrederik** [comment]
Thanks, I guess the best way would be to just make sure ADB is always listening on a TCP port and not on a Unix socket.

I'll look into this & get back to you.

**Comment by qmfrederik** [comment]
@PhilippCh, sorry for that!

Can you give v2.0.257 a try? In that version, we always assume the connection will be an IP connection (that's the default for adb); if anyone wants to use madb on a Debian/Ubuntu server they can manually specify a UnixSocket and we'll connect to that socket instead.

Long story short, should work out of the box now unless you're on Debian/Ubuntu and using their patched version of adb.

**Comment by PhilippCh** [comment]
Seems to be working fine now, thanks a lot! 👍 

With the new build I'm receiving this error (http://stackoverflow.com/questions/31992705/vs2015-project-no-longer-runs-in-debug-mode) for SharpAdbClient.dll though. Any way around that?

**Comment by qmfrederik** [comment]
@PhilippCh , I'm guessing you're seeing this error because we include the debug symbols for SharpAdbClient in the NuGet package.

Just to test this theory, could you try to delete the `SharpAdbClient.pdb` file in `packages\SharpAdbClient.2.0.254\lib\net45` and your project's output folder, and let me know whether you still get this error message?

Thanks!

**Comment by PhilippCh** [comment]
Unfortunately, this didn't fix the issue. I do have the SharpAdbClient.Extensions project in my solution (if that makes a difference), though like in the StackOverflow I linked, all configurations are set to Debug/x86.

**Comment by qmfrederik** [comment]
This issue is quite old. The original problem - macOS compatibility - has been fixed and I've never been able to reproduce the other behavior.

Feel free to open a new issue if you're still having a problem with this using the latest version of SharpAdbClient, though.
