### ISSUE TITLE
InstallPackage does not work on Android 7

### ISSUE THREAD

**Issue by KSemenenko** [quamotion/madb#82]
Hello, today faced with a problem. Installing applications does not work on Android 7.
I got an incomprehensible error "An unknown error occurred."
Until I thought of what to do ((

**Comment by qmfrederik** [comment]
Which version are you on? Can you try with the latest preview on NuGet?

See #79

**Comment by KSemenenko** [comment]
I'm using the latest version of the preview from NuGet - 2.2.0-beta386

**Comment by KSemenenko** [comment]
Can there be an easy way to call adb install -r "path to apk"?

**Comment by jonny3010** [comment]
Hi, I've also got this problem, were you able to fix it?

**Comment by KSemenenko** [comment]
Hello!
Unfortunately no. But I found that I need to use the "adb install" command
And it works fine. While I wrote my console call. it's horrible


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 12 июля 2017 г. 18:34
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Hi, I've also got this problem, were you able to fix it?

**Comment by KSemenenko** [comment]
Hi again) 
Tell me how can I run command without a "shell"?

**Comment by KSemenenko** [comment]
I do not understand how I can call the install command.
I see how you work through the shell - but it does not work.
I would be very grateful if you show an example of executing any command.


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 12 июля 2017 г. 18:34
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Hi, I've also got this problem, were you able to fix it?

**Comment by jonny3010** [comment]
So KSemenenko,
Are you just calling cmd.exe with adb install or are you still using the SharpADB library for that?

**Comment by KSemenenko** [comment]
I use this one. https://github.com/labo89/adbGUI
[https://avatars1.githubusercontent.com/u/11984646?v=3&s=400]<https://github.com/labo89/adbGUI>

GitHub - labo89/adbGUI: Wrapper for Android Debug Bridge ...<https://github.com/labo89/adbGUI>
github.com
adbGUI - Wrapper for Android Debug Bridge (ADB) written in C#


But the simultaneous installation in 2 devices does not work


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 12 июля 2017 г. 22:29
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


So KSemenenko,
Are you just calling cmd.exe with adb install or are you still using the SharpADB library for that?

**Comment by jonny3010** [comment]
Ow that looks cool, but trying to make it really simple for the people who are going to use my application. I tested it all day but with android 5, tried an android 6 device didnt work :(

I read in to Adb and how it put,s files into the device, apparently its to do with the ADB access to folders, which is /data/local/tmp/ in SharpADB for installpackage. Which in Android 6-7 might have issues with the right permissions set on the tmp folder.

I'll will try this tomorrow, uploading the APK file using the UploadFile() example then using installremotepackage. that way I can tell it to upload to the internal memory instead of temp then, delete it after install. I believe /sdcard is used on android as the internal Memory :)

**Comment by KSemenenko** [comment]
I do not understand why upload the file to the phone, if  the adb install command does everything itself))))


But if you can let me know, my application depends on it very much.


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 12 июля 2017 г. 22:52
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Ow that looks cool, but trying to make it really simple for the people who are going to use my application. I tested it all day but with android 5, tried an android 6 device didnt work :(

I read in to Adb and how it put,s files into the device, apparently its to do with the ADB access to folders, which is /data/local/tmp/ in SharpADB for installpackage. Which in Android 6-7 might have issues with the right permissions set on the tmp folder.

I'll will try this tomorrow, uploading the APK file using the UploadFile() example then using installremotepackage. that way I can tell it to upload to the internal memory instead of temp then, delete it after install. I believe /sdcard is used on android as the internal Memory :)

**Comment by jonny3010** [comment]
ideally we don't want to have to create a process and d cmd.exe /c adb install file.apk
We just want to sue the API and install the app. Not sure why we have to upload the file to the device then install it. Maybe its a limitation of the adb.exe api.

If I get it working I'll post my code in here for you.

**Comment by KSemenenko** [comment]
I'll wait for any news. If I get something, I'll let you know too.


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 12 июля 2017 г. 23:25
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


ideally we don't want to have to create a process and d cmd.exe /c adb install file.apk
We just want to sue the API and install the app. Not sure why we have to upload the file to the device then install it. Maybe its a limitation of the adb.exe api.

If I get it working I'll post my code in here for you.

**Comment by jonny3010** [comment]
So after a little trail and error this works :) tried on android 4.3 and android 6.0.1, wasnt working on 6.0.1 using packageinstall using my installAPK working a treat

```
private void InstallAPK(string apk, bool reinstall)
{
	var localFilePath = CurrentDirectory + @"\" + apk;
	string tmpandroidfolder = "/data/local/tmp/";

	var device = AdbClient.Instance.GetDevices().First();
	using (SyncService service = new SyncService(device))
	using (Stream stream = File.OpenRead(localFilePath))
	{
		service.Push(stream, tmpandroidfolder + apk, 644, File.GetLastWriteTime(localFilePath), null, System.Threading.CancellationToken.None);
	}
	PackageManager manager = new PackageManager(device);
	manager.InstallRemotePackage(tmpandroidfolder + apk, reinstall);
	AdbClient.Instance.ExecuteRemoteCommand("rm "+ tmpandroidfolder + apk, device, null);
}
```

**Comment by KSemenenko** [comment]
This too will not work in android 7.
No access to /data/local/tmp/


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 13 июля 2017 г. 11:38
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


So after a little trail and error this works :) tried on android 4.3 and android 6.0.1, wasnt working on 6.0.1 using packageinstall using my installAPK working a treat

private void InstallAPK(string apk, bool reinstall)
{
        var localFilePath = CurrentDirectory + @"\" + apk;
        string tmpandroidfolder = "/data/local/tmp/";

        var device = AdbClient.Instance.GetDevices().First();
        using (SyncService service = new SyncService(device))
        using (Stream stream = File.OpenRead(localFilePath))
        {
                service.Push(stream, tmpandroidfolder + apk, 644, File.GetLastWriteTime(localFilePath), null, System.Threading.CancellationToken.None);
        }
        PackageManager manager = new PackageManager(device);
        manager.InstallRemotePackage(tmpandroidfolder + apk, reinstall);
        AdbClient.Instance.ExecuteRemoteCommand("rm "+ tmpandroidfolder + apk, device, null);
}

**Comment by jonny3010** [comment]
Darn, I can't test that as my Android 7 Device has access to /data/local/tmp/

Do you know of anyother folder we can use?

**Comment by jonny3010** [comment]
Can you so this shell command so we can see if your device has the same folder and permissions.
`ls -ld /storage/emulated/legacy/`

**Comment by KSemenenko** [comment]
Pm I found that apk is copied normally, the pm install command itself does not work

Now working on this


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 13 июля 2017 г. 15:57
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Can you so this shell command so we can see if your device has the same folder and permissions.
ls -ld /storage/emulated/legacy/

**Comment by KSemenenko** [comment]
Its work with adb root!!!


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 13 июля 2017 г. 15:57
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Can you so this shell command so we can see if your device has the same folder and permissions.
ls -ld /storage/emulated/legacy/

**Comment by KSemenenko** [comment]
When you do this, you need to have root rights. Or that this path was in pm
AdbClient.Instance.ExecuteRemoteCommand("pm install -r \"" + tmpandroidfolder + apk + "\"", device, receiver);




________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 13 июля 2017 г. 15:57
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Can you so this shell command so we can see if your device has the same folder and permissions.
ls -ld /storage/emulated/legacy/

**Comment by KSemenenko** [comment]
Your code is 100% working.
But you need to perform adb root for the device. Otherwise there is no access to /data/local/tmp/


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 13 июля 2017 г. 15:57
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Can you so this shell command so we can see if your device has the same folder and permissions.
ls -ld /storage/emulated/legacy/

**Comment by jonny3010** [comment]
Don't you need to have a rooted device for that?

**Comment by KSemenenko** [comment]
No, but I have to run the adb root command - to start adb in the device from the root user. So I get access to the files.


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 13 июля 2017 г. 17:51
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Don't you need to have a rooted device for that?

**Comment by jonny3010** [comment]
hmm, what happens if you run them from /sdcard? same problem?

**Comment by qmfrederik** [comment]
Hi guys,

adb used to use `/data/local/tmp` for `adb install` but it seems they have changed that. There now is a built-in command for adb install. 

Basically the client sends `exec:cmd package [args]` to the adb server on the device, followed by `-S [size_of_apk]` and then streams the entire package to the device.

The adb source is here:
https://android.googlesource.com/platform/system/core/+/master/adb/commandline.cpp#1860

I'll probably get round to implementing this in the near future; feel free to pop a PR if you work on this :)

**Comment by jonny3010** [comment]
Hi qmfrederik,

I took a look to see if I could do a PR for you but I don't understand how that works. So I'll have to leave it with you, sorry. Unless KSemenenko has better c# skills than me, he might be able to do it.

**Comment by KSemenenko** [comment]
@jonny3010  @qmfrederik  Do you know how I can run "adb root" command in this library?

**Comment by KSemenenko** [comment]
Why do not you use SharpAdbClient.Extensions?
This library has everything you need! Add it to the nuget!

**Comment by jonny3010** [comment]
What do you mean? Whats in that Extensions library?

**Comment by KSemenenko** [comment]
https://github.com/quamotion/madb/tree/master/SharpAdbClient.Extensions
This is a project with very important functions

**Comment by jonny3010** [comment]
Ow right, which functions are you thinking of using and to do what?

**Comment by KSemenenko** [comment]
yes. rootcomand, device info - This is what you need.

**Comment by jonny3010** [comment]
Aw you thinking of using ExecuteRootShellCommand
Are you using a rooted Device?

**Comment by KSemenenko** [comment]
No, I'm using a not rooted device. And to execute the "pm install" command, I do not have enough rights on Android 7


________________________________
От: jonny3010 <notifications@github.com>
Отправлено: 14 июля 2017 г. 14:14
Кому: quamotion/madb
Копия: ksemenenko; Author
Тема: Re: [quamotion/madb] InstallPackage does not work on Android 7 (#82)


Aw you thinking of using ExecuteRootShellCommand
Are you using a rooted Device?

**Comment by qmfrederik** [comment]
https://github.com/quamotion/madb/commit/f35262fd033ba4537d90516dcc55e8d49f4ce31d is a first implementation of what code that supports streaming installs could look like; feel free to give it a try and let me know if it works.

**Comment by jonny3010** [comment]
Hey, I will test but can't til Thursday. If you could push a beta release to Nuget that would be great ☺

**Comment by KSemenenko** [comment]
Cool, I will test it today!

**Comment by KSemenenko** [comment]
@qmfrederik  I tested Install  method - Install(DeviceData device, Stream apk, params string[] arguments)

```cs
using(var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                    {
                        AdbClient.Instance.Install(device, fs);
                    }
```

And I Get error:

ErrorCode: 10054	
Message: Remote host forcibly closed existing connection

```
   в System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   в SharpAdbClient.TcpSocket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   в SharpAdbClient.AdbSocket.Send(Byte[] data, Int32 offset, Int32 length)
   в SharpAdbClient.AdbSocket.Send(Byte[] data, Int32 length)
   в SharpAdbClient.AdbClient.Install(DeviceData device, Stream apk, String[] arguments)
```

line 268 in AdbSocket.cs

**Comment by qmfrederik** [comment]
@KSemenenko Thanks for trying! I think this should be solved now, can you give https://github.com/quamotion/madb/commit/4819835528a7097529a7724980583b6cd8f8e0fa a try?

Thanks!

**Comment by KSemenenko** [comment]
@qmfrederik , no, its still not working

```
An error occurred while reading a response from ADB: closed
```
```
   в SharpAdbClient.AdbSocket.ReadAdbResponse()
   в SharpAdbClient.AdbClient.Install(DeviceData device, Stream apk, String[] arguments)
```
Response :
ISuccess =true
Message = "closed"
Okay = false
Timeout = false

**Comment by qmfrederik** [comment]
Hmmm, what version of adb are you using? You can check with `adb --version`

**Comment by KSemenenko** [comment]
@qmfrederik 1.0.39

**Comment by qmfrederik** [comment]
I'll see if I can try with that version. You're not passing any extra arguments to `AdbClient.Install`, right, just:

```
using(var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
    AdbClient.Instance.Install(device, fs);
}
```

**Comment by KSemenenko** [comment]
nope. the same error

An error occurred while reading a response from ADB: closed

**Comment by KSemenenko** [comment]
@qmfrederik what is your adb version?

**Comment by qmfrederik** [comment]
1.0.32; I tried with that version and an Android 8 device yesterday. You're on https://github.com/quamotion/madb/commit/4819835528a7097529a7724980583b6cd8f8e0fa, right?

**Comment by KSemenenko** [comment]
Yes, I used  4819835 @qmfrederik

**Comment by KSemenenko** [comment]
@qmfrederik  1.0.32 on Windows 10 also does not work.

**Comment by qmfrederik** [comment]
@KSemenenko I gave it another try, "works for me". Which device are you using?

**Comment by qmfrederik** [comment]
Just some additional information, this works for me on Android 8; with an Android 5.1.1 device this does not work. Instead:
- You get the following exception: `System.Net.Sockets.SocketException: 'An existing connection was forcibly closed by the remote host'`
- In adb logcat, you get the following output:  `W/sh      ( 3713): type=1400 audit(0.0:62): avc: denied { ioctl } for path="socket:[482361]" dev="sockfs" ino=482361 scontext=u:r:shell:s0 tcontext=u:r:adbd:s0 tclass=unix_stream_socket permissive=0`

I believe this is because Android 5.1.1 doesn't support streaming installs (in particular, this fix from 2015 seems relevant: https://android.googlesource.com/platform/external/sepolicy/+/f4d39ca%5E%21/).

So check which Android version you are using and let me know what results you get.

**Comment by KSemenenko** [comment]
@qmfrederik I will check. It seems this is what you need. I just checked on android 5 and 6

**Comment by qmfrederik** [comment]
@KSemenenko You should be able to detect whether an Android device supports the "new" way of uploading APKs by calling `AdbClient.Instance.GetFeatureSet(device)`. This list should contain `AdbServerFeatures.Cmd`.

If it does, you can use `AdbClient.Instance.Install`. If not, you need to use the old method - copying the file to `/data/local/tmp` and then using the shell to install the file from there.

Hope it helps!

**Comment by KSemenenko** [comment]
on Galaxy A3 2016 and Android 7 streaming doesn't work (((

**Comment by jonny3010** [comment]
@KSemenenko just wondering what happens if you use cmd and do adb install?
